server:
  port: 8181
spring:
  main:
    show_banner: false
  profiles:
    active: production
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm
  jpa:
    hibernate:
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy