logging:
  level: DEBUG

spring:
  datasource:
    initialize: true
    schema: classpath:test/schema.sql
    data: classpath:test/data.sql
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

custom:
  management:
    security:
      access: hasIpAddress('127.0.0.1') or hasIpAddress('0:0:0:0:0:0:0:1')
  remote:
    attachment-prefix: prefix/

log-api:
    uri: https://log.apitest.cc.ncu.edu.tw/log/api
